### ISSUE TITLE
Cannot find module '../util/validators'

### ISSUE THREAD

**Issue by m00g33k** [scaffold-js/generator-scaffold-js#9]
I'm having problems whenever I try to create a project. 

```
module.js:341
    throw err;
    ^

Error: Cannot find module '../util/validators'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-scaffold-js/app/index.js:11:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

OS: Ubuntu 14.04 LTS
Node version: v5.8.0
NPM version: 3.7.3
YO version: 1.7.0

**Comment by fermi2n** [comment]
Same here:

OSX El capitan
Node: 5.11.0
npm: 3.8.7
yo: 1.7.0

**Comment by fluky** [comment]
Thanks for the reports.  Looks like it was a package issue.  Can you update and retest?

**Comment by m00g33k** [comment]
Fixed! The generator works properly now. 

PS: Thanks for developing this project. Coming from a JHipster fanatic trying hard to switch to NodeJS this is like a gift from the heavens. :smile:

**Comment by fluky** [comment]
Well it comes from a JHipster fan who has never liked Java so hopefully it's a good fit :).  Thanks for the feedback.

**Comment by m00g33k** [comment]
It is!  Thanks for making this happen. Can't wait for alpha-2 release with entity generators!
